### ISSUE TITLE
set_acl no "action" parameter

### ISSUE THREAD

**Issue by dmeads89** [Isilon/isilon_sdk_8_0_python#13]
There is no "action" parameter for set_acl in the NameSpaceApi that I can see. This means that ACL setting is defaulting to replace, update option isn't available. Is this expected? Thanks

**Comment by bdd4329** [comment]
I'm having the same problem. This is a serious limitation of the API because adding a new ACE wipes out inherited ACEs.

**Comment by tenortim** [comment]
Issue writeup with links to the appropriate documentation:

The OneFS "PUT /ns/access_point/path?acl" endpoint has an action field that can be set to either "update" or "replace". This is distinct from the "op" field in each ACE that can be "add", "replace", or "delete". The latter is available in [AclObject](https://github.com/Isilon/isilon_sdk_python/blob/v8.2.1/docs/AclObject.md) but the former seems to be missing. It's not in the [NamespaceAcl](https://github.com/Isilon/isilon_sdk_python/blob/v8.2.1/docs/NamespaceAcl.md) object but it's not a parameter to  [set_acl()](https://github.com/Isilon/isilon_sdk_python/blob/v8.2.1/docs/NamespaceApi.md#set_acl) method either, at least according to the documentation.

**Comment by dmeads89** [comment]
Agreed action is available in the API but isn't in the SDK. I believe the SDK is generated by swagger and in future releases 8.2.1 it is still missing I think. Please can this be updated correctly in the 8.2.2 release of the SDK?

**Comment by nalinkanwar** [comment]
Fixed in Isilon SDK v0.2.10

https://github.com/Isilon/isilon_sdk/commit/8b9871f8ae2abf9adbce9dd0cf8ac86c5810c00a
