### ISSUE TITLE
Extra test package included with the SDK

### ISSUE THREAD

**Issue by tucked** [Isilon/isilon_sdk_8_0_python#15]
``` sh
wget 'https://files.pythonhosted.org/packages/f5/cd/0a77a5a938e2ede0d102d39b01da89bdb52b97ccf5e8a4510ae8de248131/isi-sdk-8-1-1-0.2.5.tar.gz'
tar xf isi-sdk-8-1-1-0.2.5.tar.gz
cd isi-sdk-8-1-1-0.2.5/
python
```
``` python
>>> from setuptools import find_packages
>>> find_packages()
['test', 'isi_sdk_8_1_1', 'isi_sdk_8_1_1.models', 'isi_sdk_8_1_1.api']
```
`test` shadows [a stdlib module](https://docs.python.org/3/library/test.html) and [a PyPI package](https://pypi.org/project/test/), neither of which are a big deal, but I suspect this is unintentional.

One remedy would be to move packages meant to be shipped into a `src/` directory as described in https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure
``` sh
mkdir src
git mv isi_sdk/ src/
echo 'graft src' >> MANIFEST.in
vim setup.py
```
``` python
    package_dir={'': 'src'},
    packages=setuptools.find_packages('src'),
```

**Comment by nalinkanwar** [comment]
Fixed in latest release v0.3.0
