### ISSUE TITLE
Missing equalivant of `isi_classic domain list` in PAPI

### ISSUE THREAD

**Issue by jorschra** [Isilon/isilon_sdk_8_0_python#22]
Although we can set/delete domainmarks using the jobs api, there is no way to get the current domainmarks for a path.

**Comment by vboddui** [comment]
@jorschra 

Have you tried the `/platform/worm/domains?describe`


> 

```
Resource URL: /platform/worm/domains

    Overview: This resource is a list of all the Write Once Read Many (WORM)
              domains on your cluster.
```

**Comment by sjorge** [comment]
~~Doesn't look like there is anything in the sdk that talks to that endpoint?~~
Found it, let me try and I'll get back to you.

https://github.com/Isilon/isilon_sdk_python/blob/22006d18041b9fb7858ce05c4328b757dc53df24/isi_sdk_8_2_2/docs/WormApi.md#list_worm_domains

**Comment by sjorge** [comment]
This enpoint does not see the domain marks (in this case we're interested interested in the SnapRevert one.

The return is: `{'domains': [], 'resume': None, 'total': 0}`

**Comment by nalinkanwar** [comment]
Closing as inactive; Seems like missing feature in API itself.
Please file this as a feature request/enhancement to OneFS using official support channels. This Issues page is for SDK related issues only.
