### ISSUE TITLE
Unable to create directories or setacls using API unless running as root

### ISSUE THREAD

**Issue by jorschra** [Isilon/isilon_sdk_8_0_python#23]
Currently when you talk to PAPI as any user that is not 'root' (Same for using the WebUI), you can't create directories or set acls if the user does not have permisisons on the parent directory or target dir/file.

This is annoying if you use the API with 'service accounts' from AD, and basically means some scripts need to login with root.

**Comment by nalinkanwar** [comment]
Please file this as a feature request/enhancement to OneFS using official support channels. This Issues page is for SDK related issues only.
