### ISSUE TITLE
Want ability to filter on path with list_snapshot_snapshots

### ISSUE THREAD

**Issue by jorschra** [Isilon/isilon_sdk_8_0_python#27]
When having a lot of shares list_snapshot_snapshots can be slow, it would be nice to be able to specify a path filter like with list_nfs_exports, list_quotes_quota, ...

**Comment by nalinkanwar** [comment]
Please file this as a feature request/enhancement to OneFS using official support channels. This Issues page is for SDK related issues only.

**Comment by jorschra** [comment]
> Please file this as a feature request/enhancement to OneFS using official support channels. This Issues page is for SDK related issues only.

That is what originally happened, but I was told to file them here instead by the support team. (Well, if they even had a vague idea of what I was talking about) I'll see if I can find all the original SR's and link them to the issues and shoot this of my our rep instead.

**Comment by nalinkanwar** [comment]
Ah yes, you might have to include the actual APIs instead of SDK function names where you want the improvement in. For that function, it would be improvements to `GET /platform/snapshot/snapshots` API.
