### ISSUE TITLE
isi_sdk_8_1_1.NamespaceApi get_acl AclObject inherit_flags wrong list returned

### ISSUE THREAD

**Issue by ut0f9t** [Isilon/isilon_sdk_8_0_python#30]
Hi
inherit_flags list[str] returned by the API is only a list of True variables. It is not possible to know the inherit object set.
  {'accessrights': ['dir_gen_read',
                           'dir_gen_write',
                           'dir_gen_execute',
                           'std_delete'],
          'accesstype': 'allow',
          'inherit_flags': [True, True],
          'op': None,
...............................................

Should be OneFS ACE inheritance list string as object_inherit, container_inherit, inherit_only, no_prop_inherit and inherited_ace instead

**Comment by shilpiarya** [comment]
We have already fixed this issue in the latest package of SDK https://github.com/Isilon/isilon_sdk_python/tree/Isilon_SDK_v0.2.11/isi_sdk_8_1_1/isi_sdk_8_1_1

Please upgrade your sdk 8.1.1 package and retry.

**Comment by shilpiarya** [comment]
This issue is duplicate of https://github.com/Isilon/isilon_sdk_python/issues/18

**Comment by ut0f9t** [comment]
sorry for the delay to say thank you its working fine
