### ISSUE TITLE
Is Isilon SDK backward compatible with oneFs versions?

### ISSUE THREAD

**Issue by nehatomar12** [Isilon/isilon_sdk_8_0_python#31]
Hello
I am building snapshot orchestration for DELL Isilon OneFS
I am using python SDK, but I don't want to bind it with oneFs version  
I try to use isi_sdk_8_2_2 for oneFs versions 8.0, 8.1.2, 8.2.1 but it seems the SDK API's are not backward compatible.

is it mandatory to use same SDK version that is of oneFs version?

**Comment by tenortim** [comment]
Hi @nehatomar12,
The APIs are versioned so yes, there is backwards-compatibility. The way that it works is that if you, for example, use the /3 version of an endpoint (the version that matches OneFS 8.0.0.x), that endpoint still exists in 8.1, 8.1.2, etc. and continues to offer the same API. So the API is bardwards-compatible.
The SDK uses the API, but we build multiple versions against the different OneFS versions and each of these uses the newest API endpoints available.

So, the short answer is that, if you want to use the SDK to build code that works against 8.0, 8.1.2, and 8.2.1, you must use the 8.0 version of the SDK and if the functionality available in 8.0 is sufficient, then that is all that you need to do.

If you want to be able to utilize newer functionality in e.g. 8.2.0 but still support older releases, you'd need to handle that yourself, by, for instance, importing multiple different versions of the SDK and using the appropriate version based off the target OneFS version.
