### ISSUE TITLE
Is there any way we can get changelist entries for oneFs version 8.0, 8.0.1, 8.1.0, 8.1.1, 8.2.0

### ISSUE THREAD

**Issue by nehatomar12** [Isilon/isilon_sdk_8_0_python#32]
I check the SDK API's for fetching changelist entries
GET /platform/8/snapshot/changelists/{Changelist}/entries

is only available for SDK 8.2.1, 8.2.2, 9.0

is there any way we can get changelist entries for older oneFS versions (8.0, 8.0.1, 8.1.0, 8.1.1, 8.2.0)

**Comment by tenortim** [comment]
Hello @nehatomar12,
The OneFS API did not support changelist entries in OneFS 8.2.0 and below. You can only get a list of LINs, and the look up detail on each LIN returned separately. Example below, first system is running 8.2.2, second system is running 8.2.0.

```
ubuntu-server:~$ curl -sk -u root:XXX 'https://cse-sea-h500-1:8080/platform' | grep -i changelist
/1/snapshot/changelists
/1/snapshot/changelists/<CHANGELIST>
/8/snapshot/changelists/<CHANGELIST>/entries
/8/snapshot/changelists/<CHANGELIST>/entries/<ID>
/1/snapshot/changelists/<CHANGELIST>/lins
/1/snapshot/changelists/<CHANGELIST>/lins/<LIN>
ubuntu-server:~$ curl -sk -u root:XXX 'https://cse-s210-1:8080/platform' | grep -i changelist
/1/snapshot/changelists
/1/snapshot/changelists/<CHANGELIST>
/1/snapshot/changelists/<CHANGELIST>/lins
/1/snapshot/changelists/<CHANGELIST>/lins/<LIN>
```

As you can see, the "entries" endpoints were added in version 8 of the API which corresponds to OneFS version 8.2.1.

**Comment by nehatomar12** [comment]
@tenortim 
thanks for your help 👍 

so changelist API is supported for oneFs version 8.2.1 onwards

I am new to Isilon can you tell me what exactly is this LINS API 
I can't find any documentation related to it

is it provide the same info as of changelist entries?

**Comment by tenortim** [comment]
Hi @nehatomar12,
A LIN is "logical inode number" because there are multiple on-disk inode mirrors because protection is part of the filesystem.
It has been some time since I tried it, but I think to get the information, you need to call the '/lins' endpoint to get a list of affected lins, then query each of then using the `/1/snapshot/changelists/<CHANGELIST>/lins/<LIN>` endpoint.

**Comment by nalinkanwar** [comment]
Closing as completed; Functionality is supported in latter versions and looks like they got the help they wanted.
