### ISSUE TITLE
deadlock - api client

### ISSUE THREAD

**Issue by lmeguira** [Isilon/isilon_sdk_8_0_python#36]
this code version generated by swagger code generator is exposed to deadlocks.
more details here - https://bugs.python.org/issue39360

isilon api client use multiprocessing.pool.Pool for async calls. 
12 dummy processes are allocated and at the end are joined when the api_client object being deleted.
sometimes (not frequent) a pool thread is stuck on waiting its semaphore (lll_futex_wait wrapper).

**Comment by lmeguira** [comment]
please update on the status of this issue. as I see this was addressed in newer OpenAPI versions.

I found another issue reported in Swagger codegen with more specific info:
https://github.com/swagger-api/swagger-codegen/issues/9991

**Comment by nalinkanwar** [comment]
This is not a bug in SDK but in python itself; Please update python version to 3.8.3 or later.

This is fixed upstream in Python 3.8.3 release candidate 1 and later versions by backports.
(Release date: 2020-04-29)
Ref: https://docs.python.org/3.8/whatsnew/changelog.html#python-3-8-0-final
Search for bpo-39360
