### ISSUE TITLE
Multiple SyncJob objects?

### ISSUE THREAD

**Issue by jorschra** [Isilon/isilon_sdk_8_0_python#38]
## What I'm trying to do
Cancel a running synciq job using the rest api.

## What I tried (first attempt)
Based on the docs I didn't immediately see a way to do it via the API. Give that you can cancel such a job using the WebUI, and it uses the rest api, looking at the xhr request pointed me towards: [SyncAPI.update_sync_job()](https://github.com/Isilon/isilon_sdk_python/blob/Isilon_SDK_v0.2.11/isi_sdk_8_2_2/docs/SyncApi.md#update_sync_job)

Easy enough, that takes a `SyncJob` object and a ID.
I found the corresponding [SyncJobCreateParams()](https://github.com/Isilon/isilon_sdk_python/blob/Isilon_SDK_v0.2.11/isi_sdk_8_2_2/docs/SyncJobCreateParams.md) call to create such object!

Given that action wasn't really well documented, but from memory I recalled `isi sync jobs` takes an action as sub argument.

```isis10-1# isi sync jobs
Description:
    Manage jobs.

Required Privileges:
    ISI_PRIV_SYNCIQ

Usage:
    isi sync jobs {<action> | <subcommand>}
        [--timeout <integer>]
        [{--help | -h}]

Actions:
    cancel     Cancel running or paused jobs.
    pause      Pause running jobs.
    resume     Resume paused jobs.
    start      Start a job.
    list       View a list of jobs.
    view       View properties of a sync job.

Subcommands:
    reports    View reports for running jobs.

Options:

  Display Options:
    --timeout <integer>
        Number of seconds for a command timeout (specified as 'isi --timeout NNN <command>').
    --help | -h
        Display help for this command.

See 'isi sync jobs <subcommand> --help' for more information on a specific subcommand.
```

Putting that together I came up with:

```
                        api.update_sync_job(isi.SyncJobCreateParams(
                            id="nfs_synciq_testshare",
                            action="cancel",
                        ))
```

Which resulted in this error, so looks like action does not take cancel or a variant thereof. 

```
Traceback (most recent call last):
  File "/Users/jorschra/Documents/repos/ism/bin/ism.py", line 23, in <module>
    ism.run()
  File "/Users/jorschra/Documents/repos/ism/lib/ugent/isi/cli.py", line 127, in run
    ret_state, ret_failed, ret_stats = mgr.apply()
  File "/Users/jorschra/Documents/repos/ism/lib/ugent/isi/manager/export.py", line 100, in apply
    if not self.apply_sync(share_name, location=share_loc):
  File "/Users/jorschra/Documents/repos/ism/lib/ugent/isi/manager/sync.py", line 159, in apply_sync
    action="cancel",
  File "/Users/jorschra/Documents/repos/ism/venv/lib/python3.6/site-packages/isi_sdk_8_2_2/models/sync_job_create_params.py", line 78, in __init__
    self.action = action
  File "/Users/jorschra/Documents/repos/ism/venv/lib/python3.6/site-packages/isi_sdk_8_2_2/models/sync_job_create_params.py", line 123, in action
    .format(action, allowed_values)
ValueError: Invalid value for `action` (cancel), must be one of ['resync_prep', 'allow_write', 'allow_write_revert', 'test']
```

Going back to the WebUI and looking at the xhr's again I noticed this:

<img width="545" alt="Screenshot 2021-03-01 at 11 12 32" src="https://user-images.githubusercontent.com/45480736/109485223-b4587d00-7a81-11eb-9b5c-b15da31c5a8b.png">

Interesting, as SyncJob doesn't have a `state` parameter! 

Simply calling 
```
api.update_sync_job({"state": "canceled"}, "_".join([self.access_zone, "synciq", name]))
```

Does work, the API accepts it and the job is cancelled! This makes me believe there are 2 SyncJob objects and the docs need updating.

**Comment by suva007** [comment]
Hey hi @jorschra , thank you for reaching out.

> Actual issue :

      **api.update_sync_job(isi.SyncJobCreateParams(
                            id="nfs_synciq_testshare",
                            action="cancel",
                        ))**
Points to take into consideration in order to cancel job using SDK  : 

> **SyncJobCreateParams() :** function basically does a **POST** request on "**7/sync/jobs**" in order to create a new JOB .

>  **Requirements for creating a JOB** : we need to have a policy , as you have mentined in above case with name "nfs_synciq_testshare".

> **Following this on a isilon cluster :** **https://<cluster_ip>:8080/platform/7/sync/jobs?describe** , we can see the  POST request body schema . Inside that you can follow up the actions field which defines the actions supported.

> Hence would like to confirm , it is a desired feature that , while at the time of creating JOB we cannot cancel it simultaneously.

# **For Creating a new JOB :** 
   from __future__ import print_function
   import time
   import isi_sdk_9_0_0
   from isi_sdk_9_0_0.rest import ApiException
   from pprint import pprint
  
   configuration = isi_sdk_9_0_0.Configuration()
   configuration.host = 'https://<cluster_ip>:8080'
   configuration.username = 'username'
   configuration.password = 'password'
   configuration.verify_ssl = False
  
   api_instance = isi_sdk_9_0_0.SyncApi(isi_sdk_9_0_0.ApiClient(configuration))
   sync_job = isi_sdk_9_0_0.SyncJobCreateParams(id="123") # SyncJobCreateParams |

   try:
       api_response = api_instance.create_sync_job(sync_job)
       pprint(api_response)
   except ApiException as e:
       print("Exception when calling SyncApi->create_sync_job: %s\n" % e)

> In order to modify the state of any job ,we have : 

               api.update_sync_job({"state": "canceled"}, "_".join([self.access_zone, "synciq", name]))
  As you mentioned does a PUT call in the backend and therefore does the needful.

> In coming days we will surely improve the documentation for the same , by providing the supported parameters list for ease of usage.


Thanks&Regards
Suvansh Arora

**Comment by shilpiarya** [comment]
Savanah replied the customer question, therefore closing the issue.
