### ISSUE TITLE
Hang issues while running isilon_sdk on python 3.8

### ISSUE THREAD

**Issue by rajendraindukuri** [Isilon/isilon_sdk_8_0_python#39]
Hi,

I am using isilon_sdk to perform provisioning operations on PowerScale. It used to work fine when we were using python 3.6.x. But when we recently upgraded our env to 3.8.x, we are seeing hang issues while connecting to API

When we went through the python documentation, we saw few hang issues with python 3.8 but looks like they got fixed now
Same can be referred from this link https://bugs.python.org/issue38744

Do you have any plans to handle this in near future? Thanks

**Comment by rajendraindukuri** [comment]
Any updates on this ?

**Comment by nalinkanwar** [comment]
This is not a bug in SDK but in python itself; Please update python version to 3.8.3 or later.

This is fixed upstream in Python 3.8.3 release candidate 1 and later versions by backports.
(Release date: 2020-04-29)
Ref: https://docs.python.org/3.8/whatsnew/changelog.html#python-3-8-0-final
Search for bpo-39360
