### ISSUE TITLE
Need Help on Isilon SmartConnect FQDN.

### ISSUE THREAD

**Issue by mukeshguptakc** [Isilon/isilon_sdk_8_0_python#40]
Hello,

We are working on getting the DELL EMC PowerScale configuration using the Smart Connect SSIP / Zone FQDN.
And we are able to configure Smart connect service IP and get a Smart connect zone FQDN from which we get the re-routing to individual node IPs.

We have a query that is there a API to get the Smart connect zone identified and details regarding it.
This would help us to know whether an DELL EMC PowerScale is configured through Node IP or Smart Connect Zone.
 
We currently use the ‘get_cluster_external_ips’ in the same way do we have an API to figure out the smart connect Zone FQDN.

**Comment by tucked** [comment]
If I'm understanding correctly, you are trying to tell what SmartConnect names are configured on a particular cluster?

SmartConnect zones are configured per-pool.. You can get network pools with [`isi_sdk_9_0_0.NetworkApi().get_network_pools()`](https://github.com/Isilon/isilon_sdk_python/blob/a371f438f542568edb8cda35e929e6b300b1177c/isi_sdk_9_0_0/docs/NetworkApi.md#get_network_pools) and check the resulting [`sc_dns_zone` field](https://github.com/Isilon/isilon_sdk_python/blob/a371f438f542568edb8cda35e929e6b300b1177c/isi_sdk_9_0_0/docs/NetworkPool.md) to see if SC is configured on that pool.

Does that help?

**Comment by mukeshguptakc** [comment]
thanks, @tucked.
it is resolved and i could list down and fetch all the smartConnect zones.
