### ISSUE TITLE
Question on  -- get_ads_provider_search()

### ISSUE THREAD

**Issue by globeid-dev** [Isilon/isilon_sdk_8_0_python#42]
https://github.com/Isilon/isilon_sdk_python/blob/Isilon_SDK_v0.2.11/isi_sdk_8_2_2/docs/AuthProvidersApi.md#get_ads_provider_domain

Hello,
I like to know what's the expected value for **_id-arg_** in the api.  

 It certainly is not the user-id that I had used to get the API-basic HTTP authorization.  How/where do I find/get the value for the id. 
Thanks

'# create an instance of the API class
api_instance = isi_sdk_8_2_2.AuthProvidersApi(isi_sdk_8_2_2.ApiClient(configuration))
id = 'id_example' 
scope = 'scope_example' 

try:
    api_response = api_instance.get_ads_provider_domains(id, scope=scope)
    pprint(api_response)`

**Comment by tucked** [comment]
I believe it is the name of an AD auth provider
(e.g. see available/valid options with `isi auth ads list` or `isi auth ads list -v | grep Name`).

**Comment by globeid-dev** [comment]
Thanks. 

Do you know of a API in isilon-python-sdk that can provide such AD-auth-provider ?.

**Comment by tucked** [comment]
Try `list_providers_ads`:
https://github.com/Isilon/isilon_sdk_python/blob/Isilon_SDK_v0.2.11/isi_sdk_8_2_2/docs/AuthApi.md#list_providers_ads

**Comment by globeid-dev** [comment]
> Try `list_providers_ads`:
> https://github.com/Isilon/isilon_sdk_python/blob/Isilon_SDK_v0.2.11/isi_sdk_8_2_2/docs/AuthApi.md#list_providers_ads

Thank you
