### ISSUE TITLE
Support float values for smartquota limit attributes

### ISSUE THREAD

**Issue by kuttattz** [Isilon/isilon_sdk_8_0_python#46]
Hi,
There is a request from one of our customers to support float values for the following smartquota parameters in QuotaQuotaThresholds :
- advisory
- hard
- soft

**More details about our environment** :-
**sdk versions** :  9_0_0
**oneFs versions**: 9.2 & 9.1
**python versions**: 3.9

Can you please let us know if you planned this as part of your upcoming releases.
Thanks

**Comment by nalinkanwar** [comment]
Please file this as a feature request/enhancement to OneFS using official support channels. This Issues page is for SDK related issues only.
