### ISSUE TITLE
How is the SDK licensed?

### ISSUE THREAD

**Issue by tucked** [Isilon/isilon_sdk_8_0_python#48]
The only info I could find says `UNKOWN` in `PKG-INFO` in [the latest published sdist](https://files.pythonhosted.org/packages/2f/e9/9434bf664f1c37ccc6f643894a60339c8b7210645103f442c6abd420002e/isi-sdk-9-0-0-0.2.12.tar.gz):
```
Metadata-Version: 1.0
Name: isi-sdk-9-0-0
Version: 0.2.12
Summary: Isilon SDK
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: sdk@isilon.com
License: UNKNOWN
...
```
Is it MIT like `isilon_sdk`?
https://github.com/Isilon/isilon_sdk/blob/9ca3991dc52ef0e5766b83ce604eff9dfaad0563/LICENSE

**Comment by nalinkanwar** [comment]
`License: MIT License (MIT)`

This is fixed in latest release: https://pypi.org/project/isilon-sdk/
