### ISSUE TITLE
Isilon FSA reports (FsaResultsApi.get_result_directories)

### ISSUE THREAD

**Issue by Kay-Kay83** [Isilon/isilon_sdk_8_0_python#5]
Hello Everyone,

I have a question regarding the isi_sdk_8_1_0.FSAResultsAPI.get_result_directories () method.
I am trying to extract the result from this method, the latest report using the id as '0' . Unfortunately this does not work. I am sure that there is a small point that I am missing here.

Would appreciate any assistance that is provided.

```import isi_sdk_8_1_0
import urllib3
import sys
import argparse
urllib3.disable_warnings()

# configure username and password
config = isi_sdk_8_1_0.Configuration()
config.username = "UserName"
config.password = "Passsword"
config.verify_ssl = False

# Configure host
config.host = 'https://xxx.xxx.xxx:8080'
api_client = isi_sdk_8_1_0.ApiClient(config)
clus_api = isi_sdk_8_1_0.ClusterApi(api_client)
fsa_results = isi_sdk_8_1_0.FsaResultsApi(api_client)

clus_stats = clus_api.get_cluster_statfs().__dict__
f_bavail = clus_stats['_f_bavail']
print(f_bavail)

results = fsa_results.get_result_directories('0', path='/ifs')
print(results)
```

# Output/Error

isi_sdk_8_1_0.rest.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Date': 'Mon, 30 Apr 2018 13:25:31 GMT', 'Server': 'Apache/2.2.31 (FreeBSD) mod_ssl/2.2.31 OpenSSL/1.0.2j-fips mod_fastcgi/2.4.6', 'Allow': 'GET, HEAD', 'Connection': 'close', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json', 'X-Pad': 'avoid browser bug'})
HTTP response body:
{
"errors" :
[

{
"code" : "AEC_EXCEPTION",
"message" : "basic_string"
}
]
}

**Comment by Atomicology** [comment]
@Kay-Kay83: Due to the limitations of the FSA API on OneFS, if you need to reference `/ifs` as the path, then I would recommend using the following method:
```
fsa_results.get_result_directory(2, 0)
```
That will query the logical i-node of `/ifs` (i.e. 2) for the latest FSA report (i.e. 0).

The `get_result_directories` method only works with `path` query arguments that specify a subdirectory of `/ifs`. For example, the following queries should work:
```
fsa_results.get_result_directories(0, path='/ifs/home')
fsa_results.get_result_directories(0, path='/ifs/data')
```

**Comment by nalinkanwar** [comment]
Closing as inactive;
If required, Please file this as a feature request/enhancement to OneFS using official support channels. This Issues page is for SDK related issues only.
