### ISSUE TITLE
Is this SDK still maintained?

### ISSUE THREAD

**Issue by wardy3** [Isilon/isilon_sdk_8_0_python#57]
I've moved a lot of my code over to the SDK from homegrown code but we are now several versions ahead of 9.1

Is it possible to generate the SDK ourselves from the Isilon API `?describe`?

thanks for all the work supporting the SDK :)

**Comment by nalinkanwar** [comment]
Yes, we just released a new version supporting up to OneFS version 9.5.0.0!
