### ISSUE TITLE
Code relies on basic auth to function

### ISSUE THREAD

**Issue by ngie-eign** [Isilon/isilon_sdk_8_0_python#59]
A change was made in the 9.x series that moved from basic auth to HTTP sessions. The SDK (as it stands) requires basic auth to function, so interfacing with OneFS will fail when basic auth is no longer available by default.
The SDK requiring basic auth to function is a very bad security posture for a variety of reasons.
Given that the code interfaces with PAPI using isi.rest instead of isi.papi.basepapi, session support will need to be bolted on to the SDK.
Using isi.papi.basepapi probably makes a whole lot more sense though, since it implements session handlers under the covers.

**Comment by tucked** [comment]
This looks like session auth:
https://github.com/Isilon/isilon_sdk_python/blob/a76bec4087528b16679c54f4c9e1200a590b47bd/isi_sdk_9_1_0/isi_sdk_9_1_0/api_client.py#L536-L557

**Comment by ngie-eign** [comment]
> This looks like session auth:
> 
> https://github.com/Isilon/isilon_sdk_python/blob/a76bec4087528b16679c54f4c9e1200a590b47bd/isi_sdk_9_1_0/isi_sdk_9_1_0/api_client.py#L536-L557

Yeah, that's it. This issue is invalid.
