### ISSUE TITLE
list_smb_shares method appears to have wrong url

### ISSUE THREAD

**Issue by carlilek** [Isilon/isilon_sdk_8_0_python#6]
https://github.com/Isilon/isilon_sdk_python/blob/000ceae67695c80ffab7ee93da5708210d237af6/isi_sdk/api/protocols_api.py#L9682

This line calls for platform/4/protocols/smb/shares, but the url I am seeing on my clusters is platform/1/protocols/smb/shares. the 4 path returns a 404: 

ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 01 May 2018 01:15:43 GMT', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json', 'Server': 'Apache/2.2.31 (FreeBSD) mod_ssl/2.2.31 OpenSSL/1.0.2j-fips mod_fastcgi/2.4.6'})
HTTP response body: 
{
"errors" : 
[

{
"code" : "AEC_NOT_FOUND",
"message" : "Path not found: /4/protocols/smb/shares."
}
]
}

**Comment by carlilek** [comment]
when I change this line to '/platform/1/protocols/smb/shares', 'GET', the call works as expected.

**Comment by Atomicology** [comment]
@carlilek: Platform API version 4 was introduced in OneFS 8.0.1, so it appears that you are using either the `isi-sdk-8-0-1` or `isi-sdk-8-1-0` Python package. If your cluster is running an earlier version of OneFS, then you need to use the Python package that was built against that cluster version. Packages `isi-sdk-7-2` and `isi-sdk-8-0` are available for earlier major releases.

**Comment by carlilek** [comment]
Aha! I forgot my old cluster was on 8.0.0.4. Sorry for the dumb question.


--Ken


Sent from my <advertising redacted>

On May 1, 2018, at 12:06 PM, Brandon Krueger <notifications@github.com> wrote:




@carlilek: Platform API version 4 was introduced in OneFS 8.0.1, so it appears that
 you are using either the isi-sdk-8-0-1 or isi-sdk-8-1-0 Python package. If your cluster is running an earlier version of OneFS, then you need to use the Python package that was built against that cluster version. Packages
isi-sdk-7-2 and isi-sdk-8-0 are available for earlier major releases.
—
You are receiving this because you were mentioned.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

**Comment by Atomicology** [comment]
No worries. Yes, then `isi-sdk-8-0` is the package that you will need.
