### ISSUE TITLE
Allow removal of share permissions (in addition to allowing/denying)

### ISSUE THREAD

**Issue by Pavan-Mudunuri** [Isilon/isilon_sdk_8_0_python#60]
Hi
There is a request from one of our customers to support allow removal of share permissions (in addition to allowing/denying) for SMB shares.

Can you please let us know if you planned this as part of your upcoming releases or any other alternative method to do the same.

Thanks
Pavan
Ansible Team

**Comment by nalinkanwar** [comment]
Please file this as a feature request/enhancement to OneFS using official support channels. This Issues page is for SDK related issues only.
